### ISSUE TITLE
Login to the mobile application

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rvm-mobile#1]
As a DSU agent I want to be able to login to the mobile application.

![First screen](https://user-images.githubusercontent.com/15039873/58743806-7bdbc900-83ed-11e9-895f-1e698318c9bd.png)

**Comment by RaduCStefanescu** [comment]
@ Corneliu Prodescu in SF

**Comment by RaduCStefanescu** [comment]
Can be closed, it was implemented in #9 and #10

**Comment by cosminbosutar** [comment]
The main functionality is done.
Bugs are in #35.
