### ISSUE TITLE
Implement main menu of the application

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rvm-mobile#2]
As a DSU agent I want to be able to choose the actions I want to take from the menu of the mobile application.

![Main Menu](https://user-images.githubusercontent.com/15039873/58743824-cb21f980-83ed-11e9-91b5-8f416ede82a1.png)
![Frame](https://user-images.githubusercontent.com/15039873/58743825-ccebbd00-83ed-11e9-9855-89f1689af9a8.png)

**Comment by cosminbosutar** [comment]
The main functionality is done.
