### ISSUE TITLE
[Mobile app] Atfer I click select prim-ajutor a new pop-up appears

### ISSUE THREAD

**Issue by overeha** [code4romania/rvm-mobile#25]
After I select prim-ajutor I get a pop-up with SMURD for some reason. Please check.
![Screenshot_20190808-133511](https://user-images.githubusercontent.com/45068169/62697766-2838bd80-b9e4-11e9-89dc-68e082f699e6.jpg)

**Comment by cosminbosutar** [comment]
Solved
