### ISSUE TITLE
[Mobile app] Please center the information on screen

### ISSUE THREAD

**Issue by overeha** [code4romania/rvm-mobile#26]
Center the contents of the screen. Add a bigger drop shadow on the boxes to make it more obvious they are clickable - you can also put the boxes one under the other if you increase the font size. 

![Screenshot_20190808-131845](https://user-images.githubusercontent.com/45068169/62697838-574f2f00-b9e4-11e9-8fec-8909bbfdb341.jpg)

**Comment by cosminbosutar** [comment]
Solved
