### ISSUE TITLE
[Mobile app] Please config the UAT lists

### ISSUE THREAD

**Issue by overeha** [code4romania/rvm-mobile#28]
Make sure that the user can select both the County and the village/commune/city when performing a search or adding a volunteer or allocating one. 

Example page:
![Screenshot_20190808-133948](https://user-images.githubusercontent.com/45068169/62698023-cc226900-b9e4-11e9-8655-a5431413f89b.jpg)

**Comment by cosminbosutar** [comment]
Solved
