### ISSUE TITLE
Validate volunteer

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rvm-mobile#3]
As a DSU agent I want to be able to validate a volunteer. 
As a DSU agent I want to be able search for a volunteer based on CNP, name or organisation.
As a DSU agent I want to be able to view the details of a volunteer.

![Valideaza voluntar_cautare](https://user-images.githubusercontent.com/15039873/58743847-3075ea80-83ee-11e9-839c-5eeb8e5be4d7.png)
![Vezi detalii voluntar 1](https://user-images.githubusercontent.com/15039873/58743848-32d84480-83ee-11e9-9cca-94635689780c.png)

**Comment by cosminbosutar** [comment]
Solved
