### ISSUE TITLE
[Mobile app] "Aloca voluntar" doesn't work everywhere

### ISSUE THREAD

**Issue by overeha** [code4romania/rvm-mobile#32]
If I am in the "Vezi toti voluntarii" area of the app the "Aloca voluntar" function does not work. All it does is it changes the button from "Aloca Voluntar" to "Voluntar alocat" 

![Screenshot_20190808-133840](https://user-images.githubusercontent.com/45068169/62698435-cd07ca80-b9e5-11e9-92fa-02fec4c2ed99.jpg)

**Comment by cosminbosutar** [comment]
Solvd
