### ISSUE TITLE
Allocate volunteer 

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rvm-mobile#4]
As a DSU agent I want to be able to allocate a volunteer to a specific crisis situation or area, after I have checked his details in the following scenarios:
  - First allocation: Allocate a volunteer that has never been allocated before
  - Re-allocation: Allocate a volunteer that is already allocated by another DSU agent (rescue officer).

We need to create a new DB collection that will hold the following:
  - Volunteer ID
  - DSU agent ID (rescue officer ID)
  - Location: judet/localitate
  - Organization (optional)
  - created_at

![Aloca voluntar_confirmare](https://user-images.githubusercontent.com/15039873/58743855-6fa43b80-83ee-11e9-9ef6-522534803ec4.png)

**Comment by cosminbosutar** [comment]
Solved
