### ISSUE TITLE
View all volunteers

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rvm-mobile#5]
As a DSU agent I want to be able to view the whole list of volunteers.
As a DSU agent I want to be able to search through the complete list of volunteers based on location, organisation and specialisation.

![Vezi toti voluntarii](https://user-images.githubusercontent.com/15039873/58743879-d590c300-83ee-11e9-8940-89574ce418a6.png)
![Vezi toti voluntarii _selectie](https://user-images.githubusercontent.com/15039873/58743880-d88bb380-83ee-11e9-8eff-081c9f798a51.png)

**Comment by cosminbosutar** [comment]
Tested with only the location filter and it works properly.
More tests must be performed after test data is available.

**Comment by cosminbosutar** [comment]
Validated the organization filter as well.
The specialization filter didn't behave as expected.

**Comment by cosminbosutar** [comment]
Solved
