### ISSUE TITLE
Add new volunteer and organisation

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rvm-mobile#6]
As a DSU agent I want to be able to add a new volunteer and allocate him to a crisis situation.
As a DSU agent I want to be able to create a new organisation for a new volunteer I am adding to the application.

If the NGO organisation doesn't already exist, then it should be created and set to an invalid/disabled status.

The invalid/disabled NGO organisations should be available for Rescue officers to add new volunteers to it.

![Adaugă voluntar nou](https://user-images.githubusercontent.com/15039873/58743896-37e9c380-83ef-11e9-9b5c-3058e6c31d69.png)
![Adaugă organizatie noua](https://user-images.githubusercontent.com/15039873/58743898-3b7d4a80-83ef-11e9-94ae-ee8e965e1976.png)

**Comment by cosminbosutar** [comment]
Solved
